#!/bin/bash

URL=$1
NAME=$2
FOLDER="critical/"

mkdir $FOLDER

# Desktop

echo "curl --cookie \"PHPSESSID=$3\" -o ${FOLDER}${NAME}.htm $URL"
curl --cookie "PHPSESSID=$3" -o ${FOLDER}${NAME}.htm $URL

echo "critical --base . ${FOLDER}${NAME}.htm > ${FOLDER}${NAME}.css"
critical --base . ${FOLDER}${NAME}.htm > ${FOLDER}${NAME}.css

echo "curl -F \"files0=@${FOLDER}${NAME}.css\" http://srv.cnvyr.io/v1?min=css -o ${FOLDER}${NAME}.min.css"
curl -F "files0=@${FOLDER}${NAME}.css" http://srv.cnvyr.io/v1?min=css -o ${FOLDER}${NAME}.min.css

# Mobile

echo "critical  -w375 -h667 --base . ${FOLDER}${NAME}.htm > ${FOLDER}${NAME}.mobile.css"
critical  -w375 -h667 --base . ${FOLDER}${NAME}.htm > ${FOLDER}${NAME}.mobile.css

echo "curl -F \"files0=@${FOLDER}${NAME}.mobile.css\" http://srv.cnvyr.io/v1?min=css -o ${FOLDER}${NAME}.mobile.min.css"
curl -F "files0=@${FOLDER}${NAME}.mobile.css" http://srv.cnvyr.io/v1?min=css -o ${FOLDER}${NAME}.mobile.min.css

echo "Clean up"
rm ${FOLDER}${NAME}.htm ${FOLDER}${NAME}.css ${FOLDER}${NAME}.mobile.css
